### ISSUE TITLE
Compatible with Venus OS Large

### ISSUE THREAD

**Issue by mvdh02** [mpvader/dbus-p1#2]
Hello,
i'm trying to get the 2.90 version of Venus working with my P1 meter. I've found you're github posting but i don't get it to work properly. Is this version still operational??

Greetings,

**Comment by mpvader** [comment]
Hi, I haven’t used it in a long time. We did make various changes to Venus OS, in v2.80 amongst others.

so can imagine that it doesn’t work anymore. I don’t have time to look into why I’m afraid, sorry.
